# fly.toml app configuration file generated for dreamscape on 2024-04-17T11:06:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dreamscape'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
